CREATE TABLE IF NOT EXISTS `CLEAN_TABLE_NAME` (
    `ID_CLIENT` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    `SITE` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    `ADS_LINK` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    `FOR_SALE` int DEFAULT '0',
    `FOR_LEASE` int DEFAULT '0',
    `TO_BUY` int DEFAULT '0',
    `TO_LEASE` int DEFAULT '0',
    `LAND_TYPE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `ADS_DATE` date DEFAULT NULL,
    `PRICE` float DEFAULT '0',
    `PRICE_M2` float DEFAULT '0',
    `SURFACE` float DEFAULT '0',
    `USED_SURFACE` float DEFAULT '0',
    `PRO_WIDTH` float DEFAULT '0',
    `PRO_LENGTH` float DEFAULT '0',
    `LEGAL_STATUS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `PRO_CURRENT_STATUS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `PRO_DIRECTION` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `FRONTAGE` float DEFAULT '0',
    `ALLEY_ACCESS` float DEFAULT '0',
    `NB_LOTS` float DEFAULT '0',
    `PRO_UTILITIES` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `NB_ROOMS` float DEFAULT '0',
    `NB_FLOORS` float DEFAULT '0',
    `KITCHEN` float DEFAULT '0',
    `BEDROOM` float DEFAULT '0',
    `BATHROOM` float DEFAULT '0',
    `GARAGE` int DEFAULT '0',
    `TOILET` float DEFAULT '0',
    `FULL_ADDRESS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `SPLIT_HS` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `FORMAT_HS` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `SPLIT_STREET` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `FORMAT_STREET` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `SPLIT_WARD` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `SPLIT_DISTRICT` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `SPLIT_CITY` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `STREET` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `WARD` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `DISTRICT` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `CITY` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `LAT` double DEFAULT NULL,
    `LON` double DEFAULT NULL,
    `LAT_OS` double DEFAULT NULL,
    `LON_OS` double DEFAULT NULL,
    `PHOTOS` int DEFAULT '0',
    `ADS_TITLE` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `BRIEF` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `DETAILED_BRIEF` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `PRO_WIDTH_TEXT` float DEFAULT '0',
    `PRO_LENGTH_TEXT` float DEFAULT '0',
    `ALLEY_TEXT` float DEFAULT '0',
    `FRONTAGE_TEXT` float DEFAULT '0',
    `SURFACE_TEXT` float DEFAULT '0',
    `PRICE_TEXT` float DEFAULT '0',
    `DEALER_NAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `DEALER_TYPE` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `DEALER_ADDRESS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `DEALER_EMAIL` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `DEALER_TEL` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `DEALER_JOINED_DATE` date DEFAULT NULL,
    `PROJECT_NAME` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `AGENCY_NAME` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `AGENCY_ADDRESS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `AGENCY_CITY` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `AGENCY_TEL` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `AGENCY_WEBSITE` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `CHECK_CONVERT` int DEFAULT '0',
    `PRO_FLAG` int DEFAULT '0',
    `CREATED_DATE` date NOT NULL,
    `DATE_ORIGINAL` date DEFAULT NULL,
    PRIMARY KEY (`ID_CLIENT`,`SITE`,`CREATED_DATE`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;