CREATE TABLE IF NOT EXISTS `CRAWL_TABLE_NAME` (
    `ID_CLIENT` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    `SITE` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `ADS_LINK` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    `FOR_SALE` int DEFAULT '0',
    `FOR_LEASE` int DEFAULT '0',
    `TO_BUY` int DEFAULT '0',
    `TO_LEASE` int DEFAULT '0',
    `LAND_TYPE` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `ADS_DATE` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `PRICE` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `PRICE_UNIT` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `PRICE_M2` double DEFAULT '0',
    `SURFACE` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `SURFACE_UNIT` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `USED_SURFACE` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `USED_SURFACE_UNIT` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `PRO_WIDTH` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `PRO_LENGTH` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `LEGAL_STATUS` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `PRO_CURRENT_STATUS` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `PRO_DIRECTION` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `FRONTAGE` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `ALLEY_ACCESS` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `NB_LOTS` int DEFAULT '0',
    `PRO_UTILITIES` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `NB_ROOMS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `NB_FLOORS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `KITCHEN` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `BEDROOM` int DEFAULT '0',
    `BATHROOM` int DEFAULT '0',
    `GARAGE` int DEFAULT '0',
    `TOILET` int DEFAULT '0',
    `FULL_ADDRESS` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `STREET` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `WARD` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `DISTRICT` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `CITY` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `LAT` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `LON` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `PHOTOS` int DEFAULT NULL,
    `ADS_TITLE` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `BRIEF` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `DETAILED_BRIEF` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `DEALER_ID` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `DEALER_NAME` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `DEALER_TYPE` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `DEALER_ADDRESS` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `DEALER_EMAIL` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `DEALER_TEL` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `DEALER_JOINED_DATE` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `PROJECT_NAME` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `AGENCY_NAME` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `AGENCY_ADDRESS` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `AGENCY_CITY` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `AGENCY_TEL` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `AGENCY_WEBSITE` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `MINI_SITE` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `RESTAURANT` int DEFAULT '0',
    `BANK` int DEFAULT '0',
    `COFFEESHOP` int DEFAULT '0',
    `PARK` int DEFAULT '0',
    `STADIUM` int DEFAULT '0',
    `SHOPPING` int DEFAULT '0',
    `SUPERMARKET` int DEFAULT '0',
    `GYM` int DEFAULT '0',
    `SCHOOL` int DEFAULT '0',
    `CINEMA` int DEFAULT '0',
    `HOSPITAL` int DEFAULT '0',
    `AIRPORT` int DEFAULT '0',
    `ZOO` int DEFAULT '0',
    `ANIMAL_STORE` int DEFAULT '0',
    `CLOTH_STORE` int DEFAULT '0',
    `SPA` int DEFAULT '0',
    `PARKING` int DEFAULT '0',
    `NIGHT_CLUB` int DEFAULT '0',
    `ENTERTAINMENT_PARK` int DEFAULT '0',
    `BAKERY_STORE` int DEFAULT '0',
    `GROCERIES` int DEFAULT '0',
    `POST_OFFICE` int DEFAULT '0',
    `ATM` int DEFAULT '0',
    `BAR` int DEFAULT '0',
    `CHECK_CONVERT` int DEFAULT '0',
    `PRO_FLAG` int DEFAULT '0',
    `CREATED_DATE` date DEFAULT NULL,
    `ADS_DATE_ORIGINAL` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `PRICE_ORIGINAL` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `SURFACE_ORIGINAL` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    `DATE_ORIGINAL` date DEFAULT NULL,
    `USED_SURFACE_ORIGINAL` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    PRIMARY KEY (`ID_CLIENT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
